# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-8-CIS-L1-SERVER'

# https://www.cisecurity.org/cis-benchmarks
# https://resources.cisecurity.org/benchmarks
# https://complianceascode.github.io/content-pages/guides/ssg-rhel8-guide-cis_server_l1.html
description = '''
Red Hat Enterprise Linux (RHEL) 8
Center for Internet Security® (CIS) Level 1 Server
Profile ID:  xccdf_org.ssgproject.content_profile_cis_server_l1
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
'''

distro = 'rhel-8'

[customizations]
partitioning_mode = 'auto-lvm'

[customizations.kernel]
append = ''

[customizations.openscap]
profile_id = 'xccdf_org.ssgproject.content_profile_cis_server_l1'

[customizations.services]
enabled = ['crond', 'firewalld', 'systemd-journald', 'rsyslog']
disabled = ['nfs-server', 'rpcbind', 'autofs', 'bluetooth', 'nftables']
masked = []

[[customizations.filesystem]]
mountpoint = '/tmp'
size = 1073741824

# Compliance tooling for Security Content Automation Protocol (SCAP) remediation
[[packages]]
name = 'openscap-scanner'
version = '*'
[[packages]]
name = 'scap-security-guide'
version = '*'

# CCE-90843-4 Filesystem Integrity
[[packages]]
name = 'aide'
version = '*'
