# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-8'

# https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8
description = 'Red Hat Enterprise Linux (RHEL) 8'

distro = 'rhel-8'

[customizations]
# hostname = 'custombase'
# installation_device = '/dev/vda'
partitioning_mode = 'lvm'

[[customizations.disk.partitions]]
type = 'plain'
mountpoint = '/boot'
label = 'boot'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions]]
type = 'lvm'
name = 'rootvg'
minsize = '14 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'rootlv'
mountpoint = '/'
label = 'root'
fs_type = 'xfs'
minsize = '4 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'homelv'
mountpoint = '/home'
label = 'home'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'tmplv'
mountpoint = '/tmp'
label = 'tmp'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'varlv'
mountpoint = '/var'
label = 'var'
fs_type = 'xfs'
minsize = '2 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'var_loglv'
mountpoint = '/var/log'
label = 'varlog'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'var_log_auditlv'
mountpoint = '/var/log/audit'
label = 'varlogaudit'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions.logical_volumes]]
name = 'var_tmplv'
mountpoint = '/var/tmp'
label = 'vartmp'
fs_type = 'xfs'
minsize = '1 GiB'

[[customizations.disk.partitions.logical_volumes]]
fs_type = 'swap'
minsize = '512 MiB'

# [[customizations.directories]]
# path = '/etc/foo'
# mode = '0755'
# user = 'root'
# group = 'root'
# ensure_parents = false

# [[customizations.files]]
# path = '/etc/sudoers.d/ansible'
# mode = '0440'
# user = 'root'
# group = 'root'
# data = 'ansible  ALL=(ALL)  NOPASSWD: ALL'

# [customizations.firewall]
# ports = ['22:tcp', '80:tcp', 'imap:tcp', '53:tcp', '53:udp', '30000-32767:tcp', '30000-32767:udp']

# [customizations.firewall.services]
# enabled = ['ftp', 'dhcp', 'ntp']
# disabled = ['telnet']

# Anaconda installer (ISO) image type supports the following installer customizations:
# [customizations.installer]
# unattended = true
# sudo-nopasswd = ['user', '%wheel']

# [customizations.kernel]
# append = 'net.ifnames.prefix=net quiet'

# [customizations.locale]
# languages = ['en_US.UTF-8']
# keyboard = 'us'

# [customizations.openscap]
# datastream = '/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml'
# profile_id = 'xccdf_org.ssgproject.content_profile_cis'

# [customizations.openscap.tailoring]
# selected = [ 'xccdf_org.ssgproject.content_bind_crypto_policy' ]
# unselected = [ 'grub2_password' ]

# [[customizations.sshkey]]
# user = 'root'
# key = 'ssh-rsa AAAAB..REDACTED== Root Admin'

# [customizations.timezone]
# timezone = 'UTC'
# ntpservers = ['0.rhel.pool.ntp.org', '1.rhel.pool.ntp.org', '2.rhel.pool.ntp.org']

[customizations.services]
enabled = ['cloud-preconfig']
# disabled = []
# masked = []

# [[customizations.group]]
# name = 'ansible'
# gid = 888

# [[customizations.user]]
# name = 'ansible'
# description = 'Ansible Service Account'
# password = '<REDACTED>'
# key = 'ssh-rsa AAAAB..REDACTED== Ansible Service Account'
# home = '/var/lib/ansible/'
# shell = '/usr/bin/bash'
# groups = []
# uid = 888
# gid = 888

# Compliance tooling for Security Content Automation Protocol (SCAP) remediation
[[packages]]
name = 'openscap-scanner'
version = '*'
[[packages]]
name = 'scap-security-guide'
version = '*'

# Identity Management (IdM) tooling
[[packages]]
name = 'ipa-client'
version = '*'
[[packages]]
name = 'oddjob'
version = '*'
[[packages]]
name = 'oddjob-mkhomedir'
version = '*'

# POSIX ACLs for fine-grained file permission control beyond standard ugo/rwx
[[packages]]
name = "acl"
version = "*"

# CCE-88164-9 Host-based firewall
[[packages]]
name = 'firewalld'
version = '*'

# open-vm-tools traditional Guest OS Customization (GOSC) requires Perl
[[packages]]
name = 'perl-interpreter'
version = '*'

# VMware cloud-init and userdata templates for provisioning
# https://docs.redhat.com/en/documentation/red_hat_satellite/6.19/html-single/provisioning_hosts/index#Using_VMware_Cloud_Init_and_Userdata_Templates_for_Provisioning_vmware-provisioning
# NOTE - Requires On-Premise Image Builder for file templating

# Cloud-Init: Ensure Satellite certificate is trusted before dynamically include Satellite CloudInit template
# NOTE - Replace sat-1.lab.example.org with the FQDN of your Satellite Server
[[customizations.files]]
path = '/etc/systemd/system/cloud-preconfig.service'
mode = '0644'
user = 'root'
group = 'root'
data = '''
[Unit]
Description=Update system trust store to include Red Hat Satellite CA certificate
ConditionPathExists=!/etc/pki/ca-trust/source/anchors/katello-server-ca.pem
Wants=NetworkManager-wait-online.service
After=NetworkManager-wait-online.service
Before=cloud-init.service

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c 'for i in {1..30}; do /usr/bin/curl -fsS -k https://sat-1.lab.example.org/pub/katello-server-ca.crt -o /etc/pki/ca-trust/source/anchors/katello-server-ca.pem && exit 0; sleep 2; done; exit 1'
ExecStartPost=/usr/bin/update-ca-trust extract
RemainAfterExit=no

[Install]
WantedBy=cloud-init.target
'''

# Cloud-Init: Dynamically include Satellite CloudInit template
# NOTE - Replace sat-1.lab.example.org with the FQDN of your Satellite Server
[[customizations.files]]
path = '/etc/cloud/cloud.cfg.d/10_datasource.cfg'
mode = '0644'
user = 'root'
group = 'root'
data = '''
datasource_list: [NoCloud]
datasource:
  NoCloud:
    seedfrom: https://sat-1.lab.example.org/userdata/
'''

# Cloud-Init: Disable cloud-init management of network configuration (performed by open-vm-tools)
[[customizations.files]]
path = '/etc/cloud/cloud.cfg.d/01_network.cfg'
mode = '0644'
user = 'root'
group = 'root'
data = '''
network:
  config: disabled
'''

# Cloud-Init: Reduce active module set
[[customizations.files]]
path = '/etc/cloud/cloud.cfg'
mode = '0644'
user = 'root'
group = 'root'
data = '''
cloud_init_modules:
  - bootcmd
  - ssh

cloud_config_modules:
  - runcmd

cloud_final_modules:
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - scripts-user
  - phone-home

system_info:
  distro: rhel
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates
  ssh_svcname: sshd
'''

[[customizations.files]]
path = '/etc/vmware-tools/tools.conf'
mode = '0644'
user = 'root'
group = 'root'
data = '''
# Increase timeout to 10m to allow time for the Satellite Cloud-Init template to execute
[deployPkg]
wait-cloudinit-timeout = 600
'''

[[customizations.directories]]
path = '/etc/systemd/system/cloud-init.service.d'
mode = '0755'
user = 'root'
group = 'root'

[[customizations.files]]
path = '/etc/systemd/system/cloud-init.service.d/10-wait-for-vmware.conf'
mode = '0644'
user = 'root'
group = 'root'
data = '''
[Unit]
Description=Delay cloud-init until open-vm-tools is finished setting up network
ConditionPathExists=!/run/vmware-imc/cust.cfg
'''

[[customizations.directories]]
path = '/etc/systemd/system/getty@.service.d'
mode = '0755'
user = 'root'
group = 'root'

[[customizations.files]]
path = '/etc/systemd/system/getty@.service.d/wait-for-cloud-init.conf'
mode = '0644'
user = 'root'
group = 'root'
data = '''
[Unit]
Description=Delay console login prompt until cloud-init has finished
After=cloud-init.target
'''
